// 90 Curated Motivational Quotes for the 90-day transformation

export const MOTIVATIONAL_QUOTES = [
  "Day 1: The journey of a thousand miles begins with a single step. Today, you commit.",
  "Day 2: Discomfort is the price of admission for a meaningful life. Embrace the sweat.",
  "Day 3: You don't have to be extreme, just consistent. Small daily wins lead to massive results.",
  "Day 4: Your body can stand almost anything. It's your mind that you have to convince.",
  "Day 5: Good things come to those who sweat. Today's effort is tomorrow's strength.",
  "Day 6: Discipline is choosing between what you want now and what you want most.",
  "Day 7: Rest is not quitting. Recharge today, clean up your nutrition, and prepare for Week 2.",
  "Day 8: Week 2 starts now. Raise the bar on yourself. You are stronger than last Monday.",
  "Day 9: Success isn't always about greatness. It's about consistency. Consistent hard work gains success.",
  "Day 10: The only bad workout is the one that didn't happen. Get it done.",
  "Day 11: Nutrition is 80% of the game. Fuel your body with paneer, dal, and clean protein.",
  "Day 12: Success is what happens after you survive all of your mistakes.",
  "Day 13: Your posture determines your presence. Keep your shoulders back, chest proud.",
  "Day 14: Rest, reflect, and prep. Week 2 is in the books. You are building the foundation.",
  "Day 15: Halfway through Month 1. The scale might fluctuate, but the habits are solidifying.",
  "Day 16: You did not wake up today to be mediocre. Push harder in your lifts today.",
  "Day 17: Sweating is just fat crying. Keep pushing, abs are made in the kitchen and gym.",
  "Day 18: Motivation gets you started. Habit is what keeps you going.",
  "Day 19: Energy flows where attention goes. Focus on your posture and back thickness today.",
  "Day 20: Hard work beats talent when talent doesn't work hard.",
  "Day 21: Three weeks completed! A habit takes 21 days to form. You are officially locked in.",
  "Day 22: Start of Week 4. Focus on form, mind-muscle connection. Squeeze the target muscles.",
  "Day 23: The difference between try and triumph is just a little umph.",
  "Day 24: Look in the mirror. That is your only competition.",
  "Day 25: Rome wasn't built in a day, and neither is a shredded core. Patience and protein.",
  "Day 26: If it doesn't challenge you, it doesn't change you.",
  "Day 27: Fall in love with the process, and the results will follow.",
  "Day 28: Month 1 complete! You have established the routine. Now, get ready to overload.",
  "Day 29: Week 5: Enter the progressive overload phase. Try to add 2.5kg to your main lifts today.",
  "Day 30: Strength does not come from winning. Your struggles develop your strengths.",
  "Day 31: If you want something you've never had, you must be willing to do something you've never done.",
  "Day 32: Muscle is built in the recovery. Prioritize your 8 hours of sleep tonight.",
  "Day 33: A caloric deficit is a math problem, not a mystery. Stay strict to your 2050 kcal.",
  "Day 34: Do something today that your future self will thank you for.",
  "Day 35: Active recovery day. Stretch out those tight chest and hip muscles.",
  "Day 36: Week 6. Keep adding weight or reps. Do not plateau. Challenge yourself.",
  "Day 37: The secret of change is to focus all of your energy, not on fighting the old, but on building the new.",
  "Day 38: Action is the foundational key to all success. Don't think, just go to the gym.",
  "Day 39: Push yourself because no one else is going to do it for you.",
  "Day 40: You are stronger than your excuses. Creatine in, excuses out.",
  "Day 41: Definition is starting to show. Keep the focus high, no junk food.",
  "Day 42: Rest day. Plan your meals for next week. Grocery shop for tofu, paneer, and eggs.",
  "Day 43: Week 7. You are past the 40% mark. Keep grinding, chest out, posture aligned.",
  "Day 44: When you feel like quitting, think about why you started.",
  "Day 45: Halfway there! 45 days down, 45 to go. The baseline is built, now we refine.",
  "Day 46: Dedication is doing the work when no one is watching and you don't feel like doing it.",
  "Day 47: Great things never came from comfort zones.",
  "Day 48: The only limit to our realization of tomorrow will be our doubts of today.",
  "Day 49: Seven weeks complete. Stretch, rest, hydrate. 3.5L water is non-negotiable.",
  "Day 50: Week 8. Enter the zone of high intensity. The weights should feel heavy but manageable.",
  "Day 51: Focus on the upper chest. Reduce the appearance of gyno by building the pectoral shelf.",
  "Day 52: Believe you can and you're halfway there.",
  "Day 53: There are no shortcuts. Only repetitions, clean diet, and sleep.",
  "Day 54: The clock is ticking. What will you do with today's 24 hours?",
  "Day 55: Sweat is the cologne of accomplishment. Go get some.",
  "Day 56: Month 2 complete! You are 60 days in. Only 30 days left to carve out that dream physique.",
  "Day 57: Week 9: The Shred Phase begins. High focus on calorie tracking. Abs are revealing.",
  "Day 58: Be stubborn about your goals, but flexible about your methods.",
  "Day 59: You don't get the ass you want by sitting on it. Squat day!",
  "Day 60: Small progress is still progress. Trust the 90-day process.",
  "Day 61: The pain of discipline is nothing compared to the pain of regret.",
  "Day 62: Results take time. Do not lose faith because you had one off-day.",
  "Day 63: Rest and recover. We are enters the home stretch. 27 days left.",
  "Day 64: Week 10. The details matter. Every set, every rep, every gram of protein.",
  "Day 65: Keep your posture proud. You have earned this muscle, stand tall and show it.",
  "Day 66: Sweat now, shine later. The abs are almost fully visible.",
  "Day 67: Don't count the days, make the days count.",
  "Day 68: If you tire, learn to rest, not to quit.",
  "Day 69: Energy and persistence conquer all things.",
  "Day 70: 10 Weeks done. Only 20 days left. Finish what you started.",
  "Day 71: Week 11. Push your limits. This is where champions are made.",
  "Day 72: You are writing your own success story. Make today a page turner.",
  "Day 73: Push harder than yesterday if you want a different tomorrow.",
  "Day 74: Protein targets: check. Water targets: check. Posture belt: check. Keep executing.",
  "Day 75: Your mind is a powerful thing. When you fill it with positive thoughts, your life starts to change.",
  "Day 76: There is no elevator to success. You have to take the stairs.",
  "Day 77: Rest day. You're in the final sprint. Keep the mind sharp.",
  "Day 78: Week 12. The final week of training. Make every single rep count.",
  "Day 79: The only limit is the one you set in your mind.",
  "Day 80: Ten days left. Look back at Week 1. Think of how far you have come.",
  "Day 81: Dig deep. The finish line is in sight.",
  "Day 82: Do it for the 'before and after' photo. Today is the day to dominate.",
  "Day 83: You did not come this far to only come this far.",
  "Day 84: Active recovery stretching. Give your body the care it needs for the final push.",
  "Day 85: Week 13 / The Final Shred. Final 6 days. Zero excuses, 100% execution.",
  "Day 86: Almost there. Abs are showing, posture is corrected. You look like a new person.",
  "Day 87: Excellence is a habit. You are excellent.",
  "Day 88: One rep at a time. One meal at a time. One day at a time.",
  "Day 89: Tomorrow is the final weigh-in. Stay hydrated, stay clean, stay proud.",
  "Day 90: Day 90. Goal Achieved. You committed, you persisted, and you conquered. This is just the beginning of your fitness lifestyle!"
];

export const getQuoteForDay = (day) => {
  if (day < 1) return MOTIVATIONAL_QUOTES[0];
  if (day > 90) return MOTIVATIONAL_QUOTES[89];
  return MOTIVATIONAL_QUOTES[day - 1];
};
